name: GitOps.PullRequestIssueManagement - Scheduled PRs
description: Creates pull requests on a schedule
resource: repository

where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Push to live branch (scheduled publish)
      frequencies:
      - daily:
          time: 1:00
      - daily:
          time: 4:00
      - daily:
          time: 7:00
      - daily:
          time: 10:00
      - daily:
          time: 13:00
      - daily:
          time: 16:00
      - daily:
          time: 19:00
      - daily:
          time: 22:00
      filters: []
      actions:
      - createPullRequest:
          head: main
          base: live
          title: Merge main into live
          body: Please don't squash-merge this PR.
          
